version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.docker
  db:
    image: postgres:12-alpine
    restart: always
    env_file:
      - .env.docker
